# Generated by Django 5.2.4 on 2025-07-25 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('birth_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('gender_identity', models.CharField(choices=[('Lesbian', 'Lesbian'), ('Gay', 'Gay'), ('Transgender', 'Transgender'), ('Bisexual', 'Bisexual')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('po_box', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('insurance_id', models.CharField(max_length=100)),
                ('insurance_company', models.CharField(max_length=100)),
                ('policy_group', models.CharField(max_length=100)),
                ('policy_holder_name', models.CharField(max_length=100)),
                ('policy_holder_relationship', models.CharField(max_length=50)),
                ('policy_holder_dob', models.DateField()),
                ('policy_holder_address', models.TextField()),
                ('policy_holder_phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('services', models.ManyToManyField(blank=True, to='app.service')),
            ],
        ),
    ]
