# Generated by Django 5.2.4 on 2025-07-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_patient_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
