# Generated by Django 5.2.4 on 2025-07-29 21:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender_identity',
            field=models.CharField(choices=[('Straight', 'Straight'), ('Lesbian', 'Lesbian'), ('Gay', 'Gay'), ('Transgender', 'Transgender'), ('Bisexual', 'Bisexual')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='insurance_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='po_box',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='policy_group',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='policy_holder_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='policy_holder_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='policy_holder_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
