# Generated by Django 5.2.4 on 2025-10-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patientprofile_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the therapist or writer.', max_length=150, unique=True)),
                ('title', models.CharField(help_text='E.g., Dr. of Psychology, LCSW, MA', max_length=100)),
                ('bio', models.TextField(help_text='A short biography establishing their credentials and expertise.')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Authors/Clinicians',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main headline for the article.', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(help_text='The full text of the blog post. Use a rich text editor (e.g., TinyMCE) here.')),
                ('main_image', models.ImageField(help_text='The primary, featured image for the blog post.', upload_to='blog_images/')),
                ('alt_text', models.CharField(help_text='Descriptive text for the main image (CRITICAL for SEO/Accessibility).', max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_reviewed', models.BooleanField(default=False, help_text='Has this content been formally reviewed by a medical professional?')),
                ('reviewer', models.CharField(blank=True, help_text='Name or role of the person who reviewed and approved the content.', max_length=150)),
                ('seo_title', models.CharField(blank=True, help_text='Optional: Custom title tag for SEO (max 60 chars).', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Optional: Description for search engines (max 160 chars).', max_length=160)),
                ('author', models.ForeignKey(help_text='Link to the author/clinician.', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='app.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='app.category')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_date'],
            },
        ),
    ]
