# Generated by Django 5.2.4 on 2025-10-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_author_category_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
